# Generated by Django 4.2.4 on 2023-08-31 17:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('DD', 'ДД'), ('TT', 'Танк'), ('HIL', 'Хил'), ('TRADER', 'Торговец'), ('GM', 'Гильдмастер'), ('QG', 'Квестгивер'), ('FARRIER', 'Кузнец'), ('TANNER', 'Кожевник'), ('ALCHEMIST', 'Алхимик'), ('MAG', 'Мастер заклинаний')], default='DD', max_length=50)),
                ('content', models.FileField(blank=True, upload_to='')),
                ('text', models.TextField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Repsponses',
            fields=[
                ('resp_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=255)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
