# Generated by Django 4.2.4 on 2023-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.FileField(blank=True, upload_to='content/%Y/%m/%d/'),
        ),
    ]
