# Generated by Django 4.2.4 on 2023-09-13 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_posts_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repsponses',
            name='text',
        ),
        migrations.AddField(
            model_name='repsponses',
            name='resp_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('DD', 'ДД'), ('TT', 'Танк'), ('HIL', 'Хил'), ('TRADER', 'Торговец'), ('GM', 'Гильдмастер'), ('QG', 'Квестгивер'), ('FARRIER', 'Кузнец'), ('TANNER', 'Кожевник'), ('ALCHEMIST', 'Алхимик'), ('MAG', 'Мастер заклинаний')], default='DD', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.FileField(blank=True, upload_to='content/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='heading',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='repsponses',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posts', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='repsponses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
